beckham: Remove dead calls from ModFmwkProxyService.apk
stacktrace:
06-27 22:16:44.991  3826  3857 E AndroidRuntime: FATAL EXCEPTION: Binder:3826_2
06-27 22:16:44.991  3826  3857 E AndroidRuntime: Process: com.motorola.process.system, PID: 3826
06-27 22:16:44.991  3826  3857 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/motorola/android/provider/MotorolaSettings$Secure;
06-27 22:16:44.991  3826  3857 E AndroidRuntime: 	at com.motorola.modservice.fmwkwrapper.IntentReceiver.MotorolaSettings(IntentReceiver.java:243)
06-27 22:16:44.991  3826  3857 E AndroidRuntime: 	at com.motorola.modservice.fmwkwrapper.IntentReceiver.onDetach(IntentReceiver.java:309)
06-27 22:16:44.991  3826  3857 E AndroidRuntime: 	at com.motorola.modservice.fmwkwrapper.FrameworkProxyService$2.onModAttachDetach(FrameworkProxyService.java:201)
06-27 22:16:44.991  3826  3857 E AndroidRuntime: 	at com.motorola.fmwkwrapper.IFrameworkProxyService$Stub.onTransact(IFrameworkProxyService.java:142)
06-27 22:16:44.991  3826  3857 E AndroidRuntime: 	at android.os.Binder.execTransactInternal(Binder.java:1179)
06-27 22:16:44.991  3826  3857 E AndroidRuntime: 	at android.os.Binder.execTransact(Binder.java:1143)
06-27 22:16:44.991  3826  3857 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: com.motorola.android.provider.MotorolaSettings$Secure
06-27 22:16:44.991  3826  3857 E AndroidRuntime: 	... 6 more
06-27 22:16:46.122 30547 30565 E AndroidRuntime: FATAL EXCEPTION: Greybus Dispatcher
06-27 22:16:46.122 30547 30565 E AndroidRuntime: Process: com.motorola.modservice, PID: 30547
06-27 22:16:46.122 30547 30565 E AndroidRuntime: java.lang.NullPointerException: Attempt to get length of null array
06-27 22:16:46.122 30547 30565 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2432)
06-27 22:16:46.122 30547 30565 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2410)
06-27 22:16:46.122 30547 30565 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2393)
06-27 22:16:46.122 30547 30565 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2335)
06-27 22:16:46.122 30547 30565 E AndroidRuntime: 	at com.motorola.fmwkwrapper.IFrameworkProxyService$Stub$Proxy.onModAttachDetach(SourceFile:214)
06-27 22:16:46.122 30547 30565 E AndroidRuntime: 	at com.motorola.modservice.ModManagerService.g(SourceFile:2013)
06-27 22:16:46.122 30547 30565 E AndroidRuntime: 	at com.motorola.modservice.ModManagerService.a(SourceFile:1912)
06-27 22:16:46.122 30547 30565 E AndroidRuntime: 	at com.motorola.modservice.ModManagerService.a(SourceFile:823)
06-27 22:16:46.122 30547 30565 E AndroidRuntime: 	at com.motorola.modservice.ae$1.run(SourceFile:678)
06-27 22:16:46.122 30547 30565 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
06-27 22:16:46.122 30547 30565 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-27 22:16:46.122 30547 30565 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
06-27 22:16:46.122 30547 30565 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
06-27 22:16:46.122 30547 30565 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:67)